name: WLED-16MB-Build
on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/Aircoookie/WLED/archive/refs/heads/main.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        
        # Create config.csv in the temp directory
        cat <<EOF >/tmp/WLEDtemp/config.csv
        # Name,   Type, SubType, Offset,  Size, Flags
        nvs,      data, nvs,     0x9000,  0x5000,
        otadata,  data, ota,     0xe000,  0x2000,
        app0,     app,  ota_0,   0x10000, 0x640000,
        app1,     app,  ota_1,   0x650000,0x640000,
        spiffs,   data, spiffs,  0xc90000,0x360000,
        coredump, data, coredump,0xFF0000,0x10000,%
        EOF

        # Use the config.csv for board partitions
        echo '[env:custom_build]' >> platformio.ini
        echo 'extends = env:esp32-s3-devkitc-1-n16r8v' >> platformio.ini
        echo 'board_build.partitions = /tmp/WLEDtemp/config.csv' >> platformio.ini
        echo 'build_flags = ${env:esp32-s3-devkitc-1-n16r8v.build_flags} ${common.debug_flags} -D IRPIN=19 -D USERMOD_AUDIOREACTIVE' >> platformio.ini
        echo 'lib_deps = ' >> platformio.ini
        echo '  ${env:esp32-s3-devkitc-1-n16r8v.lib_deps}' >> platformio.ini
        echo '  https://github.com/blazoncek/arduinoFFT.git' >> platformio.ini

        pio run -e custom_build || pio run -e custom_build
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/*.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
